title: Kirshnee Bhagwandas # your name (or website title) here
logo: "/images/Kirshnee.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a data scientist from Cape Town. I love creating meaning from data.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/kirshnee-bhagwandas-bbb0464a/">my linkedIn profile</a> 
  <br><br>
  <a href="https://www.linkedin.com/in/kirshnee-bhagwandas-bbb0464a/">my medium articles</a> 
  <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
